<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Password</name>
   <tag></tag>
   <elementGuidId>b5d4b664-3002-461f-8e36-101f093a87c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div[2]/form/div[2]/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-password.login-form__input > div.input-text > div.form-field > label.form-field__box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>496f4200-65d9-4fa0-9b83-a74764a5e7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field__box</value>
      <webElementGuid>ad79adc0-678c-48c0-9f64-7193f3813f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password </value>
      <webElementGuid>183602f8-e9f0-485c-986f-6ec051a3a375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;login-layout&quot;]/div[@class=&quot;login-layout__page&quot;]/div[@class=&quot;login-page login-layout__content&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;input-password login-form__input&quot;]/div[@class=&quot;input-text&quot;]/div[@class=&quot;form-field&quot;]/label[@class=&quot;form-field__box&quot;]</value>
      <webElementGuid>dd438138-eb3a-414b-ae12-eb8569b9151e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div[2]/form/div[2]/div/div/label</value>
      <webElementGuid>de86a817-2d01-4e94-abc4-de6f34cb5d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[1]</value>
      <webElementGuid>b2ec6a19-7d3a-4d85-924a-08970f29efaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk Dengan Apple'])[1]/following::label[2]</value>
      <webElementGuid>5ca5b3bb-c5b5-4878-ad1a-ee93dc339bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label</value>
      <webElementGuid>ecf2f771-3893-4128-ae1e-802d6481b3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Password ' or . = 'Password ')]</value>
      <webElementGuid>785df368-6eb2-4fc1-9fd2-366c4710ed5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
