<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>b05247fc-5172-4df8-b368-8005d3e03331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pop-up-signin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pop-up-signin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8005529c-44fa-40b6-8b48-4c088123bcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>020181e9-482d-4146-9642-b2e404e4dbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action login primary</value>
      <webElementGuid>68949d0c-7a40-4d72-b179-36a3d00e7d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pop-up-signin</value>
      <webElementGuid>5e202074-e7e8-4fde-b34a-2d6910de68dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>send</value>
      <webElementGuid>c6371629-54ef-40a0-bea8-1fda7f0c0685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>7e6e57ee-ffa2-43f2-99a8-3004488b2aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cms-home cms-index-index page-layout-1column&quot;]/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;panel wrapper&quot;]/div[@class=&quot;panel header&quot;]/ul[@class=&quot;header links&quot;]/div[@id=&quot;popup-mpdal&quot;]/div[@class=&quot;login-popup-inner&quot;]/div[@class=&quot;block-content&quot;]/form[@id=&quot;login-form-popup&quot;]/div[@class=&quot;inputwrapper&quot;]/button[@id=&quot;pop-up-signin&quot;]</value>
      <webElementGuid>aa41f22a-5c05-4d13-a20c-0cc4d1e56344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pop-up-signin']</value>
      <webElementGuid>545ed607-249d-4517-8a59-da91223fa6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form-popup']/div/button</value>
      <webElementGuid>51b6431b-76d8-4a56-b94f-b1636b607d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulir ini tidak dapat dikirimkan. Mohon untuk periksa kembali informasi Anda'])[2]/following::button[1]</value>
      <webElementGuid>d0d89463-07a4-4c0b-958b-095ffe344deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa kata sandi anda?'])[1]/following::button[1]</value>
      <webElementGuid>5885e5b7-56bc-48ed-a9de-52b87e1e0f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bergabunglah dengan Kami'])[2]/preceding::button[1]</value>
      <webElementGuid>83c5523c-9c96-49ad-9391-f63f03843a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/button</value>
      <webElementGuid>7679fc7a-b21b-41e9-a7ac-3f96f839cc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'pop-up-signin' and @name = 'send' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>9f2ad70c-9833-477d-bbd4-c46351987bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
