<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata Sandi_loginpassword</name>
   <tag></tag>
   <elementGuidId>32167ee2-9fda-4e83-9bf5-04029a547e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='popup-pass']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popup-pass</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>148390a1-bede-4398-b4ae-c25ae22f6d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login[password]</value>
      <webElementGuid>e06afd81-a697-4cb8-b318-d65f1413bc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9b10aa9d-5412-4855-921f-0c5e724f860e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>5bb6cdd7-1a0a-46a0-876d-6bf246059381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popup-pass</value>
      <webElementGuid>506dfb64-bec5-492d-b74e-a3832d1271fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Kata Sandi</value>
      <webElementGuid>0875ed76-2133-45ee-9d66-cd84bcc5ac83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true}</value>
      <webElementGuid>0aa1672c-e401-4ab9-bbe8-e6e031dfb7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>cfee36f1-042d-469e-9986-68b647529ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aac4a76f-f22d-468a-8471-55ee75e1a678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cms-home cms-index-index page-layout-1column&quot;]/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;panel wrapper&quot;]/div[@class=&quot;panel header&quot;]/ul[@class=&quot;header links&quot;]/div[@id=&quot;popup-mpdal&quot;]/div[@class=&quot;login-popup-inner&quot;]/div[@class=&quot;block-content&quot;]/form[@id=&quot;login-form-popup&quot;]/fieldset[@class=&quot;fieldset login&quot;]/div[@class=&quot;field password required inputwrapper&quot;]/div[@class=&quot;control&quot;]/input[@id=&quot;popup-pass&quot;]</value>
      <webElementGuid>145e3e6c-1fab-4b0d-9a9a-06641e4bae49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popup-pass']</value>
      <webElementGuid>c802dc92-cb16-42c0-8a18-e273c9a66278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form-popup']/fieldset/div[3]/div/input</value>
      <webElementGuid>606e322e-8612-45df-a913-8380c73abaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/fieldset/div[3]/div/input</value>
      <webElementGuid>6637ddef-5356-4dcb-9d27-134d2d5aa8ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login[password]' and @type = 'password' and @id = 'popup-pass' and @title = 'Kata Sandi']</value>
      <webElementGuid>e64d0dc2-7b2f-4779-8bb6-0f0fa37b71f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
