<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_loginusername</name>
   <tag></tag>
   <elementGuidId>744dc839-c00d-438c-9fbf-d98c2e8fb3ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='popup-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popup-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bed58136-f964-43d7-b179-83f656de57d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login[username]</value>
      <webElementGuid>7f27f2c8-c949-4c8e-86d0-a37945b985df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popup-email</value>
      <webElementGuid>58666545-7bd6-4a38-9213-e328ed98a9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>10a388ef-274b-4d3d-b53e-2a7f5bb101c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>28723394-6c7a-49af-b212-83e43af44ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>95870964-476f-41ae-93b9-6bae15c69501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{'hm_email_require_1':true, 'hm-email-id-type-2':true}</value>
      <webElementGuid>05d1d2d8-4e80-410e-9c19-751066d4dc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>5720f541-3725-4405-9a16-43297b737db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5df259bf-6839-4680-ba1c-0f7a87b5f200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cms-home cms-index-index page-layout-1column&quot;]/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;panel wrapper&quot;]/div[@class=&quot;panel header&quot;]/ul[@class=&quot;header links&quot;]/div[@id=&quot;popup-mpdal&quot;]/div[@class=&quot;login-popup-inner&quot;]/div[@class=&quot;block-content&quot;]/form[@id=&quot;login-form-popup&quot;]/fieldset[@class=&quot;fieldset login&quot;]/div[@class=&quot;field email required inputwrapper&quot;]/div[@class=&quot;control&quot;]/input[@id=&quot;popup-email&quot;]</value>
      <webElementGuid>551c8655-9aca-4e89-90d5-b8319417e97e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popup-email']</value>
      <webElementGuid>2a102357-5bc4-41f2-b869-e4fe07abc3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form-popup']/fieldset/div[2]/div/input</value>
      <webElementGuid>119bc656-dec0-4b29-b9ed-33cf129d8ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/fieldset/div[2]/div/input</value>
      <webElementGuid>0b90bf72-f2c9-4406-a35f-107e9d7448b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login[username]' and @id = 'popup-email' and @type = 'email' and @title = 'Email']</value>
      <webElementGuid>27a8fb8d-2d5c-4d49-ba22-828ee18ac306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
