<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Hi, Rafiika_fa fa-caret-down</name>
   <tag></tag>
   <elementGuidId>6500bff5-460c-46ef-8dbe-6e32f5262831</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='drop2']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-caret-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e5270bdf-545f-4906-9085-f3d8c2bb55d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-caret-down</value>
      <webElementGuid>c1e51168-f645-42ea-a1c9-8780dd067eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drop2&quot;)/i[@class=&quot;fa fa-caret-down&quot;]</value>
      <webElementGuid>581b98a2-178d-413b-b48b-bdbff2e61da5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='drop2']/i</value>
      <webElementGuid>20de358d-8760-41b9-bf1c-2087571a2c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>a3a82a5b-d834-4934-8a23-2caf2921d066</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
