<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>006fca5c-cc6c-4fba-a23d-1495bd91b803</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.style__Base-sc-1jbzg3h-0.Button__StyledButton-sc-7kpwz0-3.bBfkDk.hOUAjw.LoginBox__StyledButton-sc-1ckhuwu-1.Uotrm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a57a511-4f80-431a-8c25-45c5c80ec72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b6a77841-279d-492e-b274-be99e55efa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__Base-sc-1jbzg3h-0 Button__StyledButton-sc-7kpwz0-3 bBfkDk hOUAjw LoginBox__StyledButton-sc-1ckhuwu-1 Uotrm</value>
      <webElementGuid>1e60dda8-cab4-4375-af1a-2fed2f0fccc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>f1ef1d53-b347-4737-aeea-50f80d422525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;🚐&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;Container-sc-1y5phmm-1 aybbc&quot;]/div[@class=&quot;Card-sc-1y0eaxi-0 Container__ResponsiveCard-sc-1y5phmm-0 dHPGhp hhhotX&quot;]/form[1]/button[@class=&quot;style__Base-sc-1jbzg3h-0 Button__StyledButton-sc-7kpwz0-3 bBfkDk hOUAjw LoginBox__StyledButton-sc-1ckhuwu-1 Uotrm&quot;]</value>
      <webElementGuid>447cecf4-f650-4a7c-99d2-7f4a6a915787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>47e5562c-5333-4ba4-a205-bc357a14c11d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='🚐']/div/div/div/form/button</value>
      <webElementGuid>1110eaf3-fce3-4e56-bbed-3779bb8647cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa kata sandi?'])[1]/following::button[1]</value>
      <webElementGuid>631fc3a1-0618-474f-ad23-9ac5bb500747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata sandi'])[1]/following::button[2]</value>
      <webElementGuid>2f1d8c92-7fd6-4132-8781-c4391169175a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATAU'])[1]/preceding::button[1]</value>
      <webElementGuid>9465b1eb-75fc-4aeb-9b3a-b21feae73997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>3fa09ab3-e0e1-426e-a3d2-973b09dde553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>b8049116-4703-49ce-9df5-453ec80943d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
