<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor telepon atau email_username</name>
   <tag></tag>
   <elementGuidId>3f35dd75-f519-4a92-adb4-fe9444606103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec2e57a6-9737-4b6f-858a-f9b71a2f1a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0a2ee34-ad6e-44f1-9eb7-9cba3dd88e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>ad708e21-a68a-4a69-9079-a0a7fb3875ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Nomor telepon atau email</value>
      <webElementGuid>2372d76b-c36a-47c0-9e7a-dc30e08eb80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>87f82ec9-229e-4d69-a991-4d93d6e5581c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput-sc-1a4tyms-0 hnsMhc</value>
      <webElementGuid>07d9d2f2-e65d-441c-abd4-c4e491deb9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;🚐&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;Container-sc-1y5phmm-1 aybbc&quot;]/div[@class=&quot;Card-sc-1y0eaxi-0 Container__ResponsiveCard-sc-1y5phmm-0 dHPGhp hhhotX&quot;]/form[1]/div[@class=&quot;FormItem-sc-1yo40cl-0 LoginBox__FormItem-sc-1ckhuwu-5 JfnjT fRAcET&quot;]/div[@class=&quot;PhoneInput__Container-sc-1t229ov-0 iCJKYA&quot;]/div[@class=&quot;Input__Wrapper-sc-30lp73-0 dpTtyK PhoneInput__StyledInput-sc-1t229ov-2 hwlpun&quot;]/div[@class=&quot;AnimatedBorder__Container-akctz1-0 bscLNQ&quot;]/input[@class=&quot;TextInput-sc-1a4tyms-0 hnsMhc&quot;]</value>
      <webElementGuid>bd7a17dc-286a-4ef7-86e0-1ca3e9547a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>df919040-0278-420d-82dd-912c1334e10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='🚐']/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>7f110a7f-80af-4375-8d38-d0d555733c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d72f7c60-7b99-41c5-96ff-327cb8288664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username']</value>
      <webElementGuid>8038d694-9a16-4b5a-a757-917b97d2d1c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
